name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "npx dotenv -e .env.dev -- npx prisma migrate deploy && npx dotenv -e .env.dev -- npm exec remix vite:dev"
